# Generated by Django 4.2.21 on 2025-05-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.JSONField(verbose_name="message")),
            ],
            options={
                "verbose_name": "dummy model",
                "verbose_name_plural": "dummy models",
            },
        ),
    ]
