name: Run tests

env:
  DEFAULT_PYTHON: "3.10"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Python ${{ matrix.python_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install hatch
      run: python -m pip install hatch

    - name: Tests
      run: hatch test -i py=${{ matrix.python_version }} -- --cov=. --cov-report=xml

    - name: Override coverage report source path for SonarQube Cloud
      if: ${{ matrix.python_version == env.DEFAULT_PYTHON }}
      run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

    - name: SonarQube Cloud Scan
      if: ${{ matrix.python_version == env.DEFAULT_PYTHON }}
      uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602 # v6.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
